name = "www-heiki"
compatibility_date = "2026-09-10"

main = "@astrojs/cloudflare/entrypoints/server"

compatibility_flags = [
  "nodejs_compat",
  "global_fetch_strictly_public"
]

[assets]
binding = "ASSETS"
<<<<<<< HEAD
directory = "./dist/client"
=======
directory = "./dist"
>>>>>>> 386634d247953e6c44ce6689ed0a559e4372efe5

[[d1_databases]]
binding = "DB"
database_name = "www-heiki"
database_id = "88228084-4b6c-47ff-a7e9-d07e69848020"
